export const mockState = {
  gridStatus: "GRID_UP",
  nodes: [
    {
      node_id: 1,
      role: "master",
      soc: 94,
      light_level: 90,
      brightness_actual: 87,
      grid_status: 1,
      rssi_wifi: -41,
      rssi_espnow: -58,
      online: true,
      ts: "2026-06-29T14:20:00Z",
      slave_age_ms: 0,
    },
    {
      node_id: 2,
      role: "slave",
      soc: 78,
      light_level: 75,
      brightness_actual: 73,
      grid_status: 1,
      rssi_wifi: -55,
      rssi_espnow: -62,
      online: true,
      ts: "2026-06-29T14:20:00Z",
      slave_age_ms: 18,
    },
    {
      node_id: 3,
      role: "slave",
      soc: 61,
      light_level: 60,
      brightness_actual: 58,
      grid_status: 1,
      rssi_wifi: null,
      rssi_espnow: -71,
      online: true,
      ts: "2026-06-29T14:20:00Z",
      slave_age_ms: 36,
    },
    {
      node_id: 4,
      role: "slave",
      soc: 42,
      light_level: 40,
      brightness_actual: 38,
      grid_status: 1,
      rssi_wifi: null,
      rssi_espnow: -74,
      online: false,
      ts: "2026-06-29T14:20:00Z",
      slave_age_ms: 1250,
    },
  ],
};